specVersion: 0.2.0
name: deer-subql
version: 0.1.0
description: subql for deer network
repository: https://github.com/DeerNetwork/deer-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://mainnet-ws.deernetwork.vip'
  genesisHash: "0x037c59d6ce8a86644f2b56caf38a04635a8d74ef435e49045ea66ea5e4e18faa"
  chaintypes:
    file: ./node_modules/@deernetwork/type-definitions/dist/types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        # pallet nft
        - handler: handleNftCreated
          kind: substrate/EventHandler
          filter:
            module: nft
            method: Created
            specVersion: [100, 300]
        - handler: handleNftIssued
          kind: substrate/EventHandler
          filter:
            module: nft
            method: Issued
            specVersion: [100, 300]
        - handler: handleNftCreatedClass
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CreatedClass
        - handler: handleNftMintedToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: MintedToken
        - handler: handleNftBurnedToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: BurnedToken
        - handler: handleNftTransferredToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: TransferredToken
        - handler: handleNftUpdateTokenRoyalty
          kind: substrate/CallHandler
          filter:
            module: nft
            method: updateTokenRoyalty
            success: true
        - handler: handleNftUpdateTokenRoyaltyBeneficiary
          kind: substrate/CallHandler
          filter:
            module: nft
            method: updateTokenRoyaltyBeneficiary
            success: true

        # # pallet nftOrder
        # - handler: handleNftOrderSelling
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: Selling
        #     specVersion: [100, 300]
        # - handler: handleNftOrderDealed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: Dealed
        #     specVersion: [100, 300]
        # - handler: handleNftOrderRemoved
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: Removed
        #     specVersion: [100, 300]
        # - handler: handleCreatedNftOrder
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: CreatedOrder
        # - handler: handleDealedNftOrder
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: DealedOrder
        # - handler: handleRemovedNftOrder
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOrder
        #     method: RemovedOrder
        # - handler: handleCreatedNftOffer
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOffer
        #     method: CreatedOffer
        # - handler: handleDealedNftOffer
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOffer
        #     method: DealedOffer
        # - handler: handleRemovedNftOffer
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftOffer
        #     method: RemovedOffer

        # # pallet nftAuction
        # - handler: handleCreatedDutchAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CreatedDutchAuction
        #     specVersion: [100, 300]
        # - handler: handleCreatedEnglishAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CreatedEnglishAuction
        #     specVersion: [100, 300]
        # - handler: handleCreatedDutchAuctionV2
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CreatedDutchAuction
        #     specVersion: [400]
        # - handler: handleBidDutchAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: BidDutchAuction
        # - handler: handleCanceledDutchAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CanceledDutchAuction
        # - handler: handleRedeemedDutchAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: RedeemedDutchAuction
        # - handler: handleCreatedEnglishAuctionV2
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CreatedEnglishAuction
        #     specVersion: [400]
        # - handler: handleBidEnglishAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: BidEnglishAuction
        # - handler: handleCanceledEnglishAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: CanceledEnglishAuction
        # - handler: handleRedeemedEnglishAuction
        #   kind: substrate/EventHandler
        #   filter:
        #     module: nftAuction
        #     method: RedeemedEnglishAuction