specVersion: 0.2.0
name: deer-subql
version: 0.1.0
description: subql for deer network
repository: https://github.com/DeerNetwork/deer-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://mainnet-ws.deernetwork.vip'
  genesisHash: "0x037c59d6ce8a86644f2b56caf38a04635a8d74ef435e49045ea66ea5e4e18faa"
  chaintypes:
    file: ./node_modules/@deernetwork/type-definitions/dist/types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNftCreatedClass
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CreatedClass
        - handler: handleNftMintedToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: MintedToken
        - handler: handleNftMintedToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: BurnedToken
        - handler: handleNftTransferredToken
          kind: substrate/EventHandler
          filter:
            module: nft
            method: TransferredToken
      - handler: handleNftUpdateTokenRoyalty
        kind: substrate/CallHandler
        filter:
          module: nft
          method: updateTokenRoyalty
          success: true
      - handler: handleNftUpdateTokenRoyaltyBeneficiary
        kind: substrate/CallHandler
        filter:
          module: nft
          method: updateTokenRoyaltyBeneficiary
          success: true

        - handler: handleCreatedOrder
          kind: substrate/EventHandler
          filter:
            module: nftOrder
            method: CreatedOrder
        - handler: handleDealedOrder
          kind: substrate/EventHandler
          filter:
            module: nftOrder
            method: DealedOrder
        - handler: handleRemovedOrder
          kind: substrate/EventHandler
          filter:
            module: nftOrder
            method: RemovedOrder
        - handler: handleCreatedOffer
          kind: substrate/EventHandler
          filter:
            module: nftOffer
            method: CreatedOffer
        - handler: handleDealedOffer
          kind: substrate/EventHandler
          filter:
            module: nftOffer
            method: DealedOffer
        - handler: handleRemovedOffer
          kind: substrate/EventHandler
          filter:
            module: nftOffer
            method: RemovedOffer


        - handler: handleCreatedDutchAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: CreatedDutchAuction
        - handler: handleBidDutchAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: BidDutchAuction
        - handler: handleCanceledDutchAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: CanceledDutchAuction
        - handler: handleRedeemedDutchAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: RedeemedDutchAuction
        - handler: handleCreatedEnglishAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: CreatedEnglishAuction
        - handler: handleBidEnglishAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: BidEnglishAuction
        - handler: handleCanceledEnglishAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: CanceledEnglishAuction
        - handler: handleRedeemedEnglishAuction
          kind: substrate/EventHandler
          filter:
            module: nftAuction
            method: RedeemedEnglishAuction
